# Generated by Django 5.1.2 on 2024-10-20 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('number_of_posts', models.IntegerField(default=1)),
                ('location', models.JSONField()),
                ('eures_flag', models.BooleanField(default=False)),
                ('job_categories_codes', models.JSONField()),
                ('position_schedule_codes', models.JSONField()),
                ('employer', models.JSONField()),
                ('available_languages', models.JSONField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('json_data', models.JSONField()),
                ('first_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('update_count', models.IntegerField(default=0)),
                ('unavailable_date', models.DateTimeField(blank=True, null=True)),
                ('job_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('version_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
        ),
    ]
